version: '2'
services:

  api:
    build: ./web
    ports:
      - "43434:80"
    depends_on:
      - db
  db:
    image: postgres:11.2
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=example
  redis:
    image: redis
    container_name: cache
    expose:
      - 6379